/** @file
 *  @brief MAVLink comm protocol generated from titan.xml
 *  @see http://mavlink.org
 */
#pragma once
#ifndef MAVLINK_TITAN_H
#define MAVLINK_TITAN_H

#ifndef MAVLINK_H
    #error Wrong include order: MAVLINK_TITAN.H MUST NOT BE DIRECTLY USED. Include mavlink.h from the same directory instead or set ALL AND EVERY defines from MAVLINK.H manually accordingly, including the #define MAVLINK_H call.
#endif

#define MAVLINK_TITAN_XML_HASH -2984445879776901128

#ifdef __cplusplus
extern "C" {
#endif

// MESSAGE LENGTHS AND CRCS

#ifndef MAVLINK_MESSAGE_LENGTHS
#define MAVLINK_MESSAGE_LENGTHS {}
#endif

#ifndef MAVLINK_MESSAGE_CRCS
#define MAVLINK_MESSAGE_CRCS {{0, 50, 9, 9, 0, 0, 0}, {1, 95, 1, 1, 0, 0, 0}, {2, 88, 114, 114, 0, 0, 0}, {3, 28, 48, 48, 0, 0, 0}, {4, 158, 14, 14, 0, 0, 0}, {5, 217, 28, 28, 1, 0, 0}, {6, 104, 3, 3, 0, 0, 0}, {7, 254, 26, 26, 0, 0, 0}, {24, 24, 30, 52, 0, 0, 0}, {39, 254, 37, 38, 3, 32, 33}, {75, 158, 35, 35, 3, 30, 31}, {76, 152, 33, 33, 3, 30, 31}, {77, 143, 3, 10, 3, 8, 9}, {80, 14, 4, 4, 3, 2, 3}, {110, 84, 254, 254, 3, 1, 2}, {111, 34, 16, 18, 3, 16, 17}, {244, 95, 6, 6, 0, 0, 0}, {251, 170, 18, 18, 0, 0, 0}, {252, 44, 18, 18, 0, 0, 0}, {253, 83, 51, 54, 0, 0, 0}, {300, 217, 22, 22, 0, 0, 0}}
#endif

#include "../protocol.h"

#define MAVLINK_ENABLED_TITAN

// ENUM DEFINITIONS


/** @brief State of the water tracking device */
#ifndef HAVE_ENUM_SYSTEM_STATE
#define HAVE_ENUM_SYSTEM_STATE
typedef enum SYSTEM_STATE
{
   SYSTEM_STATE_INITALIZING=1, /*  | */
   SYSTEM_STATE_READY=2, /*  | */
   SYSTEM_STATE_FILLING_IDENTIFIED=3, /*  | */
   SYSTEM_STATE_FILLING_UNIDENTIFIED=4, /*  | */
   SYSTEM_STATE_PAUSE=5, /*  | */
   SYSTEM_STATE_UPLOADING=6, /*  | */
   SYSTEM_STATE_OVERRIDE_ON=7, /*  | */
   SYSTEM_STATE_ERROR=8, /*  | */
   SYSTEM_STATE_ENUM_END=9, /*  | */
} SYSTEM_STATE;
#endif

/** @brief  State inputs to water tracking device  */
#ifndef HAVE_ENUM_STATE_INPUT
#define HAVE_ENUM_STATE_INPUT
typedef enum STATE_INPUT
{
   STATE_INPUT_BADGE_PRESENT=1, /*  | */
   STATE_INPUT_BADGE_LEAVE=2, /*  | */
   STATE_INPUT_PULSER_PULSE=3, /*  | */
   STATE_INPUT_OVERRIDE_ON=4, /*  | */
   STATE_INPUT_OVERRIDE_OFF=5, /*  | */
   STATE_INPUT_ADMIN_START=6, /*  | */
   STATE_INPUT_ADMIN_STOP=7, /*  | */
   STATE_INPUT_UPLOAD_REQUEST=8, /*  | */
   STATE_INPUT_UPLOAD_COMPLETE=9, /*  | */
   STATE_INPUT_UPLOAD_RETRY=10, /*  | */
   STATE_INPUT_UPLOAD_ABORT=11, /*  | */
   STATE_INPUT_FILL_LIMIT=12, /*  | */
   STATE_INPUT_ENUM_END=13, /*  | */
} STATE_INPUT;
#endif

// MAVLINK VERSION

#ifndef MAVLINK_VERSION
#define MAVLINK_VERSION 2
#endif

#if (MAVLINK_VERSION == 0)
#undef MAVLINK_VERSION
#define MAVLINK_VERSION 2
#endif

// MESSAGE DEFINITIONS
#include "./mavlink_msg_state_input_event.h"
#include "./mavlink_msg_identifier.h"
#include "./mavlink_msg_water_transaction.h"
#include "./mavlink_msg_station_state.h"
#include "./mavlink_msg_station_settings.h"

// base include
#include "../common_minimal/common_minimal.h"


#if MAVLINK_TITAN_XML_HASH == MAVLINK_PRIMARY_XML_HASH
# define MAVLINK_MESSAGE_INFO {MAVLINK_MESSAGE_INFO_HEARTBEAT, MAVLINK_MESSAGE_INFO_STATE_INPUT_EVENT, MAVLINK_MESSAGE_INFO_IDENTIFIER, MAVLINK_MESSAGE_INFO_WATER_TRANSACTION, MAVLINK_MESSAGE_INFO_STATION_STATE, MAVLINK_MESSAGE_INFO_CHANGE_OPERATOR_CONTROL, MAVLINK_MESSAGE_INFO_CHANGE_OPERATOR_CONTROL_ACK, MAVLINK_MESSAGE_INFO_STATION_SETTINGS, MAVLINK_MESSAGE_INFO_GPS_RAW_INT, MAVLINK_MESSAGE_INFO_MISSION_ITEM, MAVLINK_MESSAGE_INFO_COMMAND_INT, MAVLINK_MESSAGE_INFO_COMMAND_LONG, MAVLINK_MESSAGE_INFO_COMMAND_ACK, MAVLINK_MESSAGE_INFO_COMMAND_CANCEL, MAVLINK_MESSAGE_INFO_FILE_TRANSFER_PROTOCOL, MAVLINK_MESSAGE_INFO_TIMESYNC, MAVLINK_MESSAGE_INFO_MESSAGE_INTERVAL, MAVLINK_MESSAGE_INFO_NAMED_VALUE_FLOAT, MAVLINK_MESSAGE_INFO_NAMED_VALUE_INT, MAVLINK_MESSAGE_INFO_STATUSTEXT, MAVLINK_MESSAGE_INFO_PROTOCOL_VERSION}
# define MAVLINK_MESSAGE_NAMES {{ "CHANGE_OPERATOR_CONTROL", 5 }, { "CHANGE_OPERATOR_CONTROL_ACK", 6 }, { "COMMAND_ACK", 77 }, { "COMMAND_CANCEL", 80 }, { "COMMAND_INT", 75 }, { "COMMAND_LONG", 76 }, { "FILE_TRANSFER_PROTOCOL", 110 }, { "GPS_RAW_INT", 24 }, { "HEARTBEAT", 0 }, { "IDENTIFIER", 2 }, { "MESSAGE_INTERVAL", 244 }, { "MISSION_ITEM", 39 }, { "NAMED_VALUE_FLOAT", 251 }, { "NAMED_VALUE_INT", 252 }, { "PROTOCOL_VERSION", 300 }, { "STATE_INPUT_EVENT", 1 }, { "STATION_SETTINGS", 7 }, { "STATION_STATE", 4 }, { "STATUSTEXT", 253 }, { "TIMESYNC", 111 }, { "WATER_TRANSACTION", 3 }}
# if MAVLINK_COMMAND_24BIT
#  include "../mavlink_get_info.h"
# endif
#endif

#ifdef __cplusplus
}
#endif // __cplusplus
#endif // MAVLINK_TITAN_H
